### ISSUE TITLE
Source file max column width

### ISSUE THREAD

**Issue by bmeneg** [meleca/go-bot#2]
@luizdepra @julianolf I think you guys might be more used to the golang coding style, because of that: I think it's good to use "max_line_length" and "wrap_width" on .editorconfig file, what do you guys think? If agreed, since there isn't a specific value to the language itself, what should be go-bot project's default? IMO golang remembers C simplicity, and because of that shouldn't be higher than 120 or even 100 (as a C fan-boy I would prefer 80 in fact, don't blame me for that :D).

Please give me the options/number that I add it to the file, or if anyone prefer, please add :).

**Comment by luizdepra** [comment]
Hmmm... I think 120 cols is the best option.
Nobody uses a 80 cols tty anymore. We are living the HD era! :laughing:

**Comment by bmeneg** [comment]
But but... I always split my editor vertically and than 80 is the... hahaha.

120 sounds good to me :), @luizdepra can I commit it or would you prefer to?

**Comment by luizdepra** [comment]
I'll leave it to you. ;)
